/**
 * @file ActionType.js
 * @author denglingbo
 *
 */

export default {
    RECEIVE_USER: 'RECEIVE_USER',

    RECEIVE_BOOK_LIST: 'RECEIVE_BOOK_LIST',
    RECEIVE_BOOK_DETAIL: 'RECEIVE_BOOK_DETAIL',

    RECEIVE_TOPIC: 'RECEIVE_TOPIC',
    REQUEST_TOPIC_CREATE: 'REQUEST_TOPIC_CREATE',
}
